// TODO: Update APP_NAME and contact email
const APP_NAME = "RepAI"
const CONTACT_EMAIL = "support@example.com"

export default function ConditionsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-200 px-10 py-5 flex items-center justify-between">
        <a href="/" className="text-lg font-extrabold tracking-tight text-gray-900">{APP_NAME}</a>
        <a href="/" className="text-sm font-semibold text-gray-500 hover:text-gray-900 transition-colors">← Back</a>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <p className="text-xs font-bold text-violet-600 uppercase tracking-widest mb-4">Legal</p>
        <h1 className="text-4xl font-extrabold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 font-medium mb-12">Last updated: March 2026</p>

        <div className="flex flex-col gap-10 text-gray-700">

          <section>
            <h2 className="text-lg font-extrabold text-gray-900 mb-3">1. Purpose</h2>
            <p className="text-sm font-medium leading-relaxed">
              These terms of service govern access to and use of {APP_NAME}, a SaaS platform. By creating an account, you agree to all of these terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-gray-900 mb-3">2. Access to the service</h2>
            <p className="text-sm font-medium leading-relaxed">
              You must be of legal age and have legal capacity to accept these terms. An account is personal and non-transferable. You are responsible for the confidentiality of your credentials.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-gray-900 mb-3">3. Plans and billing</h2>
            <p className="text-sm font-medium leading-relaxed mb-3">{APP_NAME} offers two plans:</p>
            <ul className="flex flex-col gap-2 text-sm font-medium mb-3">
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-violet-400 shrink-0 mt-1.5" />
                <span><strong>Free plan</strong> — limited access, no commitment, free forever</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-violet-400 shrink-0 mt-1.5" />
                {/* TODO: Update pricing */}
                <span><strong>Pro plan</strong> — $29/month, full access, cancel anytime</span>
              </li>
            </ul>
            <p className="text-sm font-medium leading-relaxed">
              Billing is monthly and automatic via Stripe. In case of non-payment, Pro access is suspended and the account reverts to Free. No refunds are made for partial periods.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-gray-900 mb-3">4. Cancellation</h2>
            <p className="text-sm font-medium leading-relaxed">
              You can cancel your subscription at any time from your dashboard. Cancellation takes effect at the end of the current billing period. Your data is retained for 30 days after cancellation, then permanently deleted.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-gray-900 mb-3">5. Acceptable use</h2>
            <p className="text-sm font-medium leading-relaxed mb-3">It is prohibited to use {APP_NAME} to:</p>
            <ul className="flex flex-col gap-2 text-sm font-medium">
              {[
                "Post illegal, misleading or discriminatory content",
                "Attempt to circumvent security measures",
                "Resell or redistribute access to third parties",
                "Generate an abusive volume of requests that could harm the service",
              ].map(item => (
                <li key={item} className="flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-violet-400 shrink-0 mt-1.5" />
                  {item}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-gray-900 mb-3">6. Intellectual property</h2>
            <p className="text-sm font-medium leading-relaxed">
              The {APP_NAME} platform, its interface, code and content are the exclusive property of {APP_NAME}. Content generated by AI from your data belongs to you. You grant us a limited license to process your data as part of the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-gray-900 mb-3">7. Limitation of liability</h2>
            <p className="text-sm font-medium leading-relaxed">
              {APP_NAME} is provided &quot;as is&quot;. AI-generated content is suggestions — you are responsible for reviewing and publishing them. We do not guarantee the accuracy or relevance of generated content. Our liability is limited to the amounts paid over the last 3 months.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-gray-900 mb-3">8. Service availability</h2>
            <p className="text-sm font-medium leading-relaxed">
              We strive to maintain maximum service availability. Occasional interruptions for maintenance may occur. We are not responsible for interruptions caused by third parties (host, AI provider, network operator).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-extrabold text-gray-900 mb-3">9. Contact</h2>
            <p className="text-sm font-medium leading-relaxed">
              For any questions regarding these terms, contact us at <a href={`mailto:${CONTACT_EMAIL}`} className="text-violet-600 hover:underline">{CONTACT_EMAIL}</a>.
            </p>
          </section>

        </div>
      </div>

      <footer className="border-t border-gray-100 px-10 py-6 flex items-center justify-between mt-8">
        <span className="font-extrabold text-gray-900">{APP_NAME}</span>
        <div className="flex gap-6 text-sm font-semibold text-gray-400">
          <a href="/confidentialite" className="hover:text-gray-900 transition-colors">Privacy</a>
          <a href="/conditions" className="text-violet-600">Terms</a>
          <a href="/support" className="hover:text-gray-900 transition-colors">Contact</a>
        </div>
      </footer>
    </div>
  )
}
